package com.personal.expensetracker.model;

public enum ExpenseCategory {
    FOOD_AND_DINING, GROCERIES, TRANSPORTATION, HOUSE, HEALTH_AND_WELLNESS, ENTERTAINMENT, SHOPPING, EDUCATION, BILLS_AND_UTILITIES, SAVINGS, MISCELLANEOUS
}